Add unit tests workflow
ElrondNetwork/elrond-go-crypto pull request #1
Opened 2021-08-01 07:46 UTC by iulianpascalau

- added unit tests github workflow
- added a new function in BLS multisigner to be used in tests

2021-08-01 12:27 UTC, iulianpascalau commented on go.mod
> +go 1.13
without this change the tests fail with the following error:
```
# github.com/herumi/bls-go-binary/bls
vendor/github.com/herumi/bls-go-binary/bls/bls.go:17:10: fatal error: mcl/bn_c384_256.h: No such file or directory
   17 | #include <mcl/bn_c384_256.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
```

2021-08-02 07:03 UTC, bogdan-rosianu requested changes

2021-08-02 07:03 UTC, bogdan-rosianu commented on .github/workflows/pr-tests.yml
> +        run: make test
empty line

2021-08-02 07:03 UTC, bogdan-rosianu commented on Makefile
> +	go test -cover -race -coverprofile=coverage.txt -covermode=atomic -v ./...
empty line

2021-08-02 07:03 UTC, bogdan-rosianu commented on signing/multisig/blsMultisig_test.go
> +func genMultiSigParamsBLS(consensusGroupSize int, ownIndex uint16) (
`generate` ?

2021-08-02 07:13 UTC, iulianpascalau commented on .github/workflows/pr-tests.yml
> +        run: make test
done

2021-08-02 07:13 UTC, iulianpascalau commented on Makefile
> +	go test -cover -race -coverprofile=coverage.txt -covermode=atomic -v ./...
done

2021-08-02 07:15 UTC, raduchis commented on signing/multisig/blsMultisig_test.go
> +func genMultiSigParamsBLS(consensusGroupSize int, ownIndex uint16) (
:+1:

2021-08-02 07:15 UTC, iulianpascalau commented on signing/multisig/blsMultisig_test.go
> +func genMultiSigParamsBLS(consensusGroupSize int, ownIndex uint16) (
old code, changed `gen` -> `generate`

2021-08-02 07:16 UTC, raduchis reviewed
small changes needed

2021-08-02 07:22 UTC, raduchis approved these changes

2021-08-02 07:29 UTC, bogdan-rosianu approved these changes

2021-08-02 07:29 UTC, merged